# Generated by Django 5.0.2 on 2024-05-04 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='booking',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
