# Generated by Django 5.0.2 on 2024-05-04 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookingapi', '0002_delete_booking_delete_movie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('ticket_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('poster', models.ImageField(upload_to='posters/')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('tickets', models.PositiveBigIntegerField(default=1)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('booking_pdf', models.FileField(blank=True, null=True, upload_to='bookings/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingapi.movie')),
            ],
        ),
    ]
