# Generated by Django 5.0.2 on 2024-05-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapi', '0004_remove_booking_booking_pdf_booking_qr_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='time',
            field=models.TimeField(max_length=200),
        ),
    ]
