# Generated by Django 5.0.2 on 2024-05-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapi', '0007_alter_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='your_date',
            field=models.DateField(default='2024-01-01'),
        ),
    ]
