# Generated by Django 5.0.2 on 2024-05-14 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapi', '0008_booking_your_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='your_date',
            new_name='date',
        ),
    ]
